### PR TITLE
Bug 1748353 Bump forecast horizon to end of 2022

### PR DESCRIPTION
**Pull request by jklukas**
See https://bugzilla.mozilla.org/show_bug.cgi?id=1748353

### CODE REVIEW

**Comment by jklukas** [comment]
cc @xluo-ds Is this job still needed?

We extended to end of 2021 in https://github.com/mozilla/forecasting/pull/40 per request of Dan and Selena, but not sure if this remains relevant in 2022.

**Review by scholtzan — APPROVED** [review]

**Comment by xluo-ds** [comment]
@jklukas I haven't got any follow-up ask from them around MAU stuff, but let me confirm with Dan.

**Comment by jklukas** [comment]
> @jklukas I haven't got any follow-up ask from them around MAU stuff, but let me confirm with Dan.

Merging this change for now so that the job continues to run, but feel free to post here with result of discussion, and we can tear down the DAG that runs this job if it's no longer needed.

**Comment by jklukas** [comment]
The failed to publish due to an error in build. I'm guessing there's some dependency that's getting pulled in without a pinned version that's causing incompatibilities.

**Comment by xluo-ds** [comment]
> 

Thanks, I will update here once I hear back from Dan.

**Comment by xluo-ds** [comment]
> > @jklukas I haven't got any follow-up ask from them around MAU stuff, but let me confirm with Dan.
> 
> Merging this change for now so that the job continues to run, but feel free to post here with result of discussion, and we can tear down the DAG that runs this job if it's no longer needed.

Sounds good! Talked to Dan, and I will update here once I hear back from him.

**Comment by jklukas** [comment]
I've tried several follow-ups to get this working, but the job is still erroring out. I've turned off the DAG for now so that we don't sink any more time into this until we have a verdict from Dan.

**Comment by xluo-ds** [comment]
@jklukas just heard from Dan that Selena confirmed it's fine to shut down the forecast on MAU.

**Comment by xluo-ds** [comment]
@jklukas side question but related, I have a notebook written in Python and would like to run as a daily job with airflow. Arkadiusz is working on it this week, I want to bring it up in case that we can reuse what we have now for the MAU forecasting.

**Comment by jklukas** [comment]
> I have a notebook written in Python and would like to run as a daily job with airflow. Arkadiusz is working on it this week, I want to bring it up in case that we can reuse what we have now for the MAU forecasting.

If some of the code here can be reused, that's great. This repo was created before the more general https://github.com/mozilla/docker-etl repo, though. If your job makes sense to express as a docker container, then it's probably best to have it live in docker-etl, using pieces of the code here as scaffolding as needed. cc @akkomar 

Given that both this MAU forecast job and the anomdtct job in this repo are no longer used, it probably makes sense to archive this repo.

**Comment by jklukas** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1749039 to track archiving of this repo.

**Pull request merged**
